### ISSUE TITLE
foundry.toml

### ISSUE THREAD

**Issue by joesmith2019** [runtimeverification/simbolik-vscode#9]
I download it, but couldn't use it.
It prompt "Could not find foundry.toml" error.
My OS is Microsoft windows 11.
Please help.

**Comment by RaoulSchaffranek** [comment]
Hi @joesmith2019!

The debugger only works for Foundry projects and expects a `foundry.toml` file in your project root folder. For more detailed instructions, you may look at our [Getting Started Guide](https://docs.runtimeverification.com/simbolik/overview/getting-started).
